server:
  port: 8080
  # SSL
  # port: 8443
  ssl:
    enabled: false
    key-store: ${CERT_PATH}/cert.p12
    key-store-password: password
    keyStoreType: PKCS12
management:
  endpoints:
    enabled-by-default: false
logging:
  register-shutdown-hook: true
  level:
    web: INFO
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    defer-datasource-initialization: true
    generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    sql:
      init:
        mode: always

  h2:
    console:
      enabled: false
  devtools:
    restart:
      enabled: false
